# Generated by Django 3.2 on 2024-03-22 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(blank=True, max_length=255, null=True, unique=True)),
                ('short_url', models.URLField(blank=True, max_length=255, null=True, unique=True)),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2024, 4, 21, 6, 50, 33, 441849))),
            ],
        ),
    ]
